/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:79225569-67be-49ba-9bc6-7c8681825648",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WxbwFYyjV",
    "aws_user_pools_web_client_id": "4sr86rfv87mq78itkhg8iqkdmd",
    "oauth": {}
};


export default awsmobile;
